version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: mani002/flask-mysql-app
    restart: always
    ports:
      - "5000-5002:80"
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql:
